server:
  port: 8300
spring:
  application:
    name: book-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#logging:
#  pattern:
#    console: "%msg%n"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html # http://localhost:8100/swagger-ui/index.html
  use-management-port: false
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,openapi,swagger-ui' # http://localhost:8100/actuator/
  server:
    port: 8101